# Credits: dub.co
# This is meant for local development only. Do not use this in production.

services:
  pullsmith-mysql:
    image: mysql:8.0
    restart: always
    environment:
      MYSQL_DATABASE: planetscale
      MYSQL_ROOT_HOST: "%"
      MYSQL_ALLOW_EMPTY_PASSWORD: "yes"
    command:
      [
        "--max_connections=1000",
        "--default-authentication-plugin=mysql_native_password",
      ]
    ports:
      - 3306:3306
    volumes:
      - pullsmith-mysql:/var/lib/mysql

  planetscale-proxy:
    image: ghcr.io/mattrobenolt/ps-http-sim:latest
    command:
      [
        "-mysql-no-pass",
        "-listen-port=3900",
        "-mysql-dbname=planetscale",
        "-mysql-addr=pullsmith-mysql",
      ]
    depends_on:
      - pullsmith-mysql
    ports:
      - 3900:3900
    links:
      - pullsmith-mysql

  redis:
    image: redis/redis-stack-server:6.2.6-v6
    ports:
      - "6379:6379"
    volumes:
      - pullsmith_redis:/data
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 5s
      retries: 5

  upstash-redis-http:
    image: hiett/serverless-redis-http:latest
    ports:
      - "8080:80"
    environment:
      - SRH_MODE=env
      - SRH_TOKEN=local_dev_token
      - SRH_CONNECTION_STRING=redis://redis:6379
    depends_on:
      redis:
        condition: service_healthy

  qdrant:
    image: qdrant/qdrant:latest
    restart: always
    ports:
      - "6333:6333"  # REST API and Web UI
      - "6334:6334"  # gRPC API
    volumes:
      - qdrant_storage:/qdrant/storage
    environment:
      - QDRANT__SERVICE__HTTP_PORT=6333
      - QDRANT__SERVICE__GRPC_PORT=6334
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:6333/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 10s

volumes:
  pullsmith-mysql:
  pullsmith_redis:
  qdrant_storage:
